global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'jutjubic-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - app-replica-1:8080
          - app-replica-2:8080
